razorpay/razorpay-magento

README.md

Fix the typo in the word Magento. 
Please also fix on https://docs.razorpay.com/v1/page/integrating-your-magento-store-with-razorpay?utm_source=tw-page&utm_medium=organic&utm_campaign=magento-tw page.

Install the latest stable version, not dev-master.

---

app/code/community/Razorpay/Payments/Helper/Data.php
app/code/community/Razorpay/Payments/Model/Paymentmethod.php
app/code/community/Razorpay/Payments/etc/config.xml
app/design/frontend/base/default/layout/razorpay.xml
app/design/frontend/base/default/template/razorpay/extensions/appzab_osc/payments.phtml
package.xml

* Fix bugs
* Add AppZab OneStepCheckout support

Add support for AppZab OneStepCheckout

---

app/code/community/Razorpay/Payments/Model/Paymentmethod.php
app/code/community/Razorpay/Payments/controllers/CheckoutController.php
app/code/community/Razorpay/Payments/etc/config.xml
js/razorpay/razorpay-utils.js
package.xml

* Add display currency and amount from quote currency and amount

Add multiple currency support

---

app/code/community/Razorpay/Payments/Model/Paymentmethod.php
package.xml

* Change order status to processing

[magento-1.x] Fix order status

---

README.md
app/code/community/Razorpay/Payments/Helper/Data.php
app/code/community/Razorpay/Payments/Model/Paymentmethod.php
app/code/community/Razorpay/Payments/controllers/CheckoutController.php
app/design/frontend/base/default/template/razorpay/checkout.phtml
package.xml

Integrated auto capture of orders API into the magento razorpay extension.

Auto capture

---

Controller/BaseController.php
Controller/Payment/Order.php
Model/PaymentMethod.php
view/frontend/web/js/view/payment/method-renderer/razorpay-method.js

Fixed all the bugs and errors. Now has a working implementation of orders API with auto-capture after testing.

Auto capture 2.x

---

Controller/Payment/Order.php
view/frontend/web/js/view/payment/method-renderer/razorpay-method.js

Magento 2.x will now support multiple currencies.

Added multi-currency support for magento 2.0

---

app/code/community/Razorpay/Payments/controllers/CheckoutController.php

Initial order state changed to new as default

---

app/code/community/Razorpay/Payments/Model/Paymentmethod.php

[inventory fix] Added a fix for decrementing invetory on order cancellation

Inventory Fix

---

app/code/community/Razorpay/Payments/Model/Paymentmethod.php

Added Razorpay option for admin orders

Add admin orders payment method list

---

app/code/community/Razorpay/Payments/Model/Paymentmethod.php

remove capture

---

app/code/community/Razorpay/Payments/Helper/Data.php

Checking if razorpayOrderId is already created to avoid double order creation.

Fixing double order creation

---

js/razorpay/razorpay-utils.js

Moving magento javascript away from prototype

Prototype fix

---

app/code/community/Razorpay/Payments/Helper/Data.php

[array fix] 

---

app/code/community/Razorpay/Payments/controllers/CheckoutController.php

Deleting quote on payment complete

[cart empty] 

---

Model/PaymentMethod.php
composer.json

SDK upgrade with verifyPaymentSignature added to magento 2

Sdk upgrade

---

view/frontend/web/js/view/payment/method-renderer/razorpay-method.js

Picking up user email from customer object when user logged in
Tested
https://github.com/razorpay/razorpay-magento/issues/25

[user logged in]

---

app/code/community/Razorpay/Payments/Helper/Data.php

[minor fixes] Removed dead code

---

composer.json

Using magento/framework 100.* in composer.json

[magento 2.1] 

---

modman

Added ability to install extension using [modman tool](https://github.com/colinmollenhour/modman):
``` bash
modman clone git@github.com:razorpay/razorpay-magento.git -b master
```

Modman file added
